### ISSUE TITLE
[design] 차크라 UI 테마 지정, 리드미 수정, 공용 컴포넌트 제작

### ISSUE THREAD

**Issue by gkdus2217** [TeamOHJO/Frontend#10]
## Description

> 차크라 UI 테마 지정, 리드미 수정, 공용 컴포넌트 제작

### Task

- [x] 차크라 UI 테마 지정
- [x] 모달 컴포넌트 제작
- [x] 토스트 팝업 컴포넌트 제작
- [x] 구현 예시 테스트 파일 추가
- [x] 리드미 수정
