### ISSUE TITLE
[refact] 장바구니, 위시리스트, 마이페이지(예약내역만) api 분리

### ISSUE THREAD

**Issue by dabin-Hailey** [TeamOHJO/Frontend#114]
## Description

> 장바구니, 위시리스트, 마이페이지(예약내역만) 페이지에서 호출하는 api 요청 함수 axios 폴더에서 분리하겠습니다.

### Task

- [x] 장바구니 API 함수 분리
- [x] 위시리스트 API 함수 분리
- [x] 마이페이지(예약내역만) API 함수 분리
- [x] 함수 이름 파스칼케이스 -> 카멜케이스로 변경
