### ISSUE TITLE
[refact] 장바구니, 위시리스트, 마이페이지(예약내역) API 함수 내부 로직 수정

### ISSUE THREAD

**Issue by dabin-Hailey** [TeamOHJO/Frontend#116]
## Description

> 장바구니, 위시리스트, 마이페이지(예약내역만) 페이지에서 호출하는 api 함수의 내부 로직을 수정합니다.

### Task

- [x] 비동기 응답(반환값)의 에러 처리까지 api 함수 내에서 작성
  - [ ] 리뷰 작성 페이지 에러 처리 부분 제거 (api 함수에서 처리할 예정) => 멘토링 이후 추가 리팩토링 예정
- [x] 비동기 응답(반환값)의 타입 없는 것에 타입 추가
