### ISSUE TITLE
[design] 뱃지 테마 및 사용법 테스트 추가

### ISSUE THREAD

**Issue by gkdus2217** [TeamOHJO/Frontend#12]
## Description

> 뱃지 테마 및 사용법 테스트 추가

### Task

- [x] 뱃지 테마 추가
- [x] 뱃지 사용법 테스트 추가
- [x] 푸터 레이아웃 추가
- [x] MainRouter 스크롤 되게 수정
