### ISSUE TITLE
[design] 숙소, 객실 상세페이지 기능 및 디자인 디테일

### ISSUE THREAD

**Issue by JeongMin83** [TeamOHJO/Frontend#26]
## Description

>  숙소, 객실 상세페이지 기능 및 디자인 디테일

### Task

할 일(숙소 상세)

- [x] 좋아요 버튼
- [x] 장바구니 툴팁
- [x] 예약하기 disabled 구현
- [x] 스크롤탑 btn
- [x] 슬라이더 디자인
- [ ] 객실 선택 sticky
- [x] 하트 누르면 슬라이드 초기화 이슈..
- [x] 객실 선택 달력/인원
- [x] 모달 토스트
- [x] 전체보기 버튼 리뷰 페이지 참고
- [x] explanation 전체보기 조건문
- [ ] 리뷰 스크롤바 수정
- [x] 지도 api
- [x] 네비게이션 연결
- [x] 장바구니 담긴 갯수
- [x] 달력 모달 하루 선택 예외처리
- [ ] 달력 모달 하루 선택 후 취소 예외처리
- [x] 사진 갤러리 페이지 or 모달
- [x] 설명 한 눈에 보기 페이지 or 모달
- [x] 목업데이터 생성
