### ISSUE TITLE
[design] 홈페이지 레이아웃 보완

### ISSUE THREAD

**Issue by turkey-kim** [TeamOHJO/Frontend#38]
## Description

> 홈페이지 레이아웃 보완

### Task

- [x] 홈페이지 점속 시 '호텔/리조트' 버튼 포커스
- [x] 좋아요버튼 추기
- [x] 이미지 슬라이드 적용
- [x] 더보기 버튼 추가 (무한스크롤 적용할지 고민)
- [x] 목데이터 추가 및 연결

### Next Task

- [ ] 비로그인 푸시 알람 기능 추가
- [ ] 로그인 상태관리 -> 네비게이션 바 적용
- [ ] 검색 모달 에러 필터링 추가 (보류)
- [ ] 캘린더 커스텀 및 한글화 (보류)
