### ISSUE TITLE
[feat] 장바구니 페이지 기능 구현 (API 연결 제외)

### ISSUE THREAD

**Issue by dabin-Hailey** [TeamOHJO/Frontend#41]
## Description

> 장바구니 페이지 기능 구현 (API 연결 제외)

### Task

- [x] 목 데이터 생성
- [x] 목 데이터 연결
- [x] atom 만들기
- [x] `결제` 라는 텍스트를 `예약`으로 변경
- [x] 결제 예상 금액 (총 금액) 계산하기
- [x] 예약하기 버튼 -> 모달 띄우기
  - [x] 모달 버튼 클릭에 따른 로직 구현
- [x] 상품 선택 (선택할 때 마다 배열에 담고 빼기)
- [x] 예약 가능 숙소 선택 삭제 기능 (api 제외)
  - [x] 선택한 상품 없을 때 예외 처리
- [x] 예약 불가능 숙소 삭제 기능 (api 제외)
  - [x] 개별 삭제 (api 제외)
  - [x] 모두 삭제 (api 제외)
- [x] 뒤로 가기 기능
- [x] 장바구니 데이터 없을 때 보여줄 컴포넌트 만들기
- [x] 체크인날짜 빠른 순서대로 정렬해서 리스팅
