### ISSUE TITLE
[feat] 네비게이션 세팅, 홈페이지 검색 필터 상태관리 세팅

### ISSUE THREAD

**Issue by turkey-kim** [TeamOHJO/Frontend#49]
## Description

> 홈페이지 api연동을 위해 세팅을 좀 해보렵니다
> 로그인 관련해서도 상태관리 해보렵니다.

### Task

- [x] 검색 필터링 상태관리
- [ ] 검색 결과 리스팅 준비 => 필터링이 바뀔 때마다 상태 reset
- [x] 로그인 상태관리 ( 쿠키값 활용 ) 
   - [x] 로그인 상태에 따른 네비게이션바 렌더링
   - [ ] 유저 이름, 전화번호 전역상태 추가 (쿠키에 저장되어 있어 x)
- [x] 달력 데이터 Mysql Datetime 포맷으로 변경 함수 작성
- [x] userRouter 추가(하연님 로직활용)
   - [x] 로딩서클 적용 (사용할지 안할지는 선택.. )
