### ISSUE TITLE
[feat] 위시리스트 페이지 기능 구현 (API 연결 제외)

### ISSUE THREAD

**Issue by dabin-Hailey** [TeamOHJO/Frontend#53]
## Description

> 위시리스트 페이지 기능 구현 (API 연결 제외)

### Task

- [x] 위시리스트 목 데이터 생성
- [x] 위시리스트 목록 불러오기
- [x] 좋아요 버튼 클릭 시 로직 (정민님 코드 참고)
- [x] location 아이콘 회색으로 바꾸기
