### ISSUE TITLE
[feat] 상세 페이지 세부 기능 추가

### ISSUE THREAD

**Issue by JeongMin83** [TeamOHJO/Frontend#58]
## Description

> 상세 페이지 세부 기능 추가

### Task

- [x] 뱃지 구분
- [x] 할인율 적용
- [x] price * day
- [x] 태그 적용
- [x] isReservation = false 가격도 처리
- [x] isReservation = false 버튼 텍스트 "예약 마감"
- [x] 좋아요 버튼 애니메이션
- [x] InfoText 줄바꿈 허용
- [x] 장바구니 툴팁, 예약하기 컴포넌트 분리(초기화 이슈)
