### ISSUE TITLE
[feat] 메인페이지 디자인 보완 및 좋아요 연동

### ISSUE THREAD

**Issue by turkey-kim** [TeamOHJO/Frontend#66]
## Description

> 메인페이지 디자인 보완 및 좋아요 연동

### Task

- [x] 가격 콤마 생성
- [x] 카드컴포넌트 배경색
- [x] 글자 배치 수정
- [x] 네비게이션바 로그아웃
- [x] 네비게이션바 z-index
- [x] footer 수정
- [x] 좋아요 연동
- [x] 페이지 이동 시 최상단설정
- [x] 네비게이션바 버그 잡기
- [x] 달력 디자인 수정
- [x] 달력 예외처리(애매 / 당일치기 버그 못잡음)
- [x] 데이터 없으면 더보기 없애기
- [x] 데이터 없으면 없다고 표시
- [ ] 검색 페이지 현재 필터링 상태 표시  => 공수 너무 많이 듭니다..
- [ ] 사진 클릭 시 이동( 이벤트 버블링 막기 ) => 보류
